

import { Translations, LanguageCode, Campaign } from './types';

export const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#AF19FF', '#FF4560'];

export const CHANNEL_FORMATS: Record<string, string[]> = {
    "Google Ads": ["Search", "PMax", "Display", "YouTube", "Demand Gen"],
    "Meta Ads": ["Darkpost", "Faceleads", "Feed", "Stories/Reels", "Feed/Stories", "Carrossel", "Video Views", "Lead Ad"],
    "LinkedIn Ads": ["Sponsored Content", "Sponsored Messaging", "Lead Gen Forms", "Dynamic Ads", "Text Ads"],
    "TikTok Ads": ["In-Feed Ads", "TopView", "Branded Hashtag Challenge", "Branded Effects"],
    "Microsoft Ads": ["Search", "Audience Network"],
    "Pinterest Ads": ["Static Pin", "Video Pin", "Carousel Pin", "Shopping Pin", "Idea Pin"],
    "X Ads": ["Promoted Ads", "Follower Ads", "X Amplify", "X Live"]
};

export const OPTIONS = {
    tipoCampanha: ["Awareness", "Alcance", "Tráfego", "Engajamento", "Geração de Leads", "Conversão", "Retargeting"],
    etapaFunil: ["Topo", "Meio", "Fundo"],
    canal: Object.keys(CHANNEL_FORMATS),
    unidadeCompra: ["CPC", "CPM", "CPV", "CPL"],
};

export const DEFAULT_METRICS_BY_OBJECTIVE: Record<string, Partial<Campaign>> = {
    "Awareness": { cpm: 15.00, ctr: 0.80, taxaConversao: 0.10, connectRate: 50, unidadeCompra: 'CPM' },
    "Alcance": { cpm: 12.00, ctr: 0.90, taxaConversao: 0.20, connectRate: 55, unidadeCompra: 'CPM' },
    "Tráfego": { cpc: 1.20, ctr: 2.00, taxaConversao: 0.50, connectRate: 80, unidadeCompra: 'CPC' },
    "Engajamento": { cpc: 1.40, ctr: 2.50, taxaConversao: 1.00, connectRate: 75, unidadeCompra: 'CPC' },
    "Geração de Leads": { cpc: 2.50, ctr: 1.50, taxaConversao: 5.00, connectRate: 85, unidadeCompra: 'CPC' },
    "Conversão": { cpc: 3.00, ctr: 2.20, taxaConversao: 8.00, connectRate: 90, unidadeCompra: 'CPC' },
    "Retargeting": { cpc: 2.80, ctr: 3.50, taxaConversao: 10.00, connectRate: 95, unidadeCompra: 'CPC' },
};

export const MONTHS_LIST = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];

export const TRANSLATIONS: Translations = {
    'pt-BR': {
        save: 'Salvar',
        cancel: 'Cancelar',
        close: 'Fechar',
        edit: 'Renomear', // "Edit" can be ambiguous, "Rename" is better for plans
        delete: 'Apagar', // General delete
        actions: 'Ações',
        language: 'Idioma',
        theme: 'Tema',
        duplicate: 'Duplicar',
        my_plans: 'Meus Planos',
        create_new_plan: 'Criar Novo Plano',
        welcome_to_masterplan: 'Bem-vindo ao MasterPlan!',
        create_first_plan: 'Vamos criar o seu primeiro plano de mídia. Como gostaria de começar?',
        create_with_ai: 'Criar Plano com IA',
        ai_description: 'Deixe a nossa inteligência artificial criar um rascunho para você.',
        start_blank: 'Começar em Branco',
        blank_description: 'Comece do zero e construa seu plano passo a passo.',
        create_from_template: 'Criar com Modelo',
        template_description: 'Comece com um plano pré-preenchido com exemplos para editar.',
        my_profile: 'Meu Perfil',
        sign_out: 'Sair',
        overview: 'Overview',
        copy_builder: 'Copy Builder',
        utm_builder: 'UTM Builder',
        keyword_builder: 'Keyword Builder',
        creative_builder: 'Creative Builder',
        detailing: 'Detalhamento',
        tools: 'Ferramentas',
        media_plan: 'Plano de Mídia',
        configure: 'Configurar',
        export: 'Exportar',
        Janeiro: 'Janeiro', Fevereiro: 'Fevereiro', Março: 'Março', Abril: 'Abril', Maio: 'Maio', Junho: 'Junho', Julho: 'Julho', Agosto: 'Agosto', Setembro: 'Setembro', Outubro: 'Outubro', Novembro: 'Novembro', Dezembro: 'Dezembro',
        "Investimento por Canal": "Investimento por Canal",
        "Investimento por Tipo de Campanha": "Investimento por Tipo de Campanha",
        "Investimento por Formato": "Investimento por Formato",
        "Investimento por Etapa Funil": "Investimento por Etapa Funil",
        "Análise Estratégica do Plano": "Análise Estratégica do Plano",
        "Editar Campanha": "Editar Campanha",
        "Nova Campanha": "Nova Campanha",
        "Sugerir Público com IA": "Sugerir Público com IA",
        "Salvar Campanha": "Salvar Campanha",
        "Configurações do Plano": "Configurações do Plano",
        "Nome da Campanha": "Nome da Campanha",
        "Logotipo": "Logotipo",
        "Cole a URL do logotipo aqui": "Cole a URL do logotipo aqui",
        "Upload": "Upload",
        "Objetivo Geral": "Objetivo Geral",
        "Público-Alvo Principal": "Público-Alvo Principal",
        "Praça": "Praça",
        "Investimento Total Planejado (R$)": "Investimento Total Planejado (R$)",
        "Resumo do Plano": "Resumo do Plano",
        "Objetivo": "Objetivo",
        "Público-Alvo": "Público-Alvo",
        "Investimento Planejado": "Investimento Planejado",
        "Investimento Previsto": "Investimento Previsto",
        "Período": "Período",
        "Analisar Plano com IA": "Analisar Plano com IA",
        "Performance por Mês": "Performance por Mês",
        "Adicionar Mês": "Adicionar Mês",
        "Invest. Total": "Invest. Total",
        "% Share": "% Share",
        "Impressões": "Impressões",
        "Alcance": "Alcance",
        "Cliques": "Cliques",
        "Conversões": "Conversões",
        "Tx. Conversão": "Tx. Conversão",
        "Totais": "Totais",
        "Investimento por Mês": "Investimento por Mês",
        "Distribuição de Investimento (Geral)": "Distribuição de Investimento (Geral)",
        "Plano de Mídia - {month}": "Plano de Mídia - {month}",
        "Gerar Ideias": "Gerar Ideias",
        "Gerando...": "Gerando...",
        "Tipo": "Tipo",
        "Funil": "Funil",
        "Canal": "Canal",
        "Formato": "Formato",
        "Budget": "Budget",
        "Orçamento Diário": "Orçamento Diário",
        "Nenhuma campanha adicionada para {month}.": "Nenhuma campanha adicionada para {month}.",
        "Totais do Mês": "Totais do Mês",
        "Distribuição de Investimento ({month})": "Distribuição de Investimento ({month})",
        "Sugestões de Criativos (IA)": "Sugestões de Criativos (IA)",
        "Gerando ideias...": "Gerando ideias...",
        "Contexto para a IA": "Contexto para a IA",
        "Descreva o produto, público, oferta e palavras-chave para guiar a IA...": "Descreva o produto, público, oferta e palavras-chave para guiar a IA...",
        "Gerar Sugestões com IA": "Gerar Sugestões com IA",
        "Títulos (Headlines)": "Títulos (Headlines)",
        "Descrições (Descriptions)": "Descrições (Descriptions)",
        "Títulos Longos (Long Headlines)": "Títulos Longos (Long Headlines)",
        "Nenhum grupo de criativos para {channel}": "Nenhum grupo de criativos para {channel}",
        "Comece adicionando um novo grupo.": "Comece adicionando um novo grupo.",
        "Para começar, adicione campanhas com canais definidos no seu plano de mídia.": "Para começar, adicione campanhas com canais definidos no seu plano de mídia.",
        "URL do Site *": "URL do Site *",
        "Campaign Source *": "Campaign Source *",
        "Campaign Medium *": "Campaign Medium *",
        "Campaign Name *": "Campaign Name *",
        "Campaign Term": "Campaign Term",
        "Campaign Content": "Campaign Content",
        "URL Gerada": "URL Gerada",
        "Salvar Link": "Salvar Link",
        "Limpar": "Limpar",
        "Links Salvos": "Links Salvos",
        "Exportar como:": "Exportar como:",
        "Data": "Data",
        "Campanha": "Campanha",
        "URL Completa": "URL Completa",
        "Nenhum link salvo ainda.": "Nenhum link salvo ainda.",
        "Adicionar Mês ao Plano": "Adicionar Mês ao Plano",
        "Mês": "Mês",
        "Meses": "Meses",
        "Editar Perfil": "Editar Perfil",
        "Nome": "Nome",
        "URL da Foto": "URL da Foto",
        "Voltar ao Dashboard": "Voltar ao Dashboard",
        "Planeamento de Mídia Inteligente": "Planeamento de Mídia Inteligente",
        "Entrar com Google": "Entrar com Google",
        "Tipo Campanha": "Tipo Campanha",
        "Etapa Funil": "Etapa Funil",
        "Unidade de Compra": "Unidade de Compra",
        "Budget (R$)": "Budget (R$)",
        "Valor da Unidade (R$)": "Valor da Unidade (R$)",
        "CPC (R$)": "CPC (R$)",
        "CPA (R$)": "CPA (R$)",
        "CPM (R$)": "CPM (R$)",
        "CTR (%)": "CTR (%)",
        "Taxa de Conversão (%)": "Taxa de Conversão (%)",
        "KPI": "KPI",
        "Novo Grupo de Criativos": "Novo Grupo de Criativos",
        "Selecione": "Selecione",
        "Rename": "Renomear", // Specifically for renaming items
        "Rename Plan": "Renomear Plano",
        "Plan Name": "Nome do Plano",
        "Copy": "(Cópia)",
        "Confirm Delete Plan": "Tem certeza que deseja apagar este plano? Esta ação não pode ser desfeita.",
        "Nenhum plano encontrado": "Nenhum plano encontrado",
        "Crie seu primeiro plano de mídia para começar.": "Crie seu primeiro plano de mídia para começar.",
        "Abrir Plano": "Abrir Plano",
        "Todos os direitos reservados.": "Todos os direitos reservados.",
        "Métricas Estimadas": "Métricas Estimadas",
        "Adicionar Primeira Campanha": "Adicionar Primeira Campanha",
        "Nome do Grupo de Criativos": "Nome do Grupo de Criativos",
        "Gerar Sugestões com IA para este campo": "Gerar Sugestões com IA para este campo",
        "Novo Grupo": "Novo Grupo",
        "Criativos para": "Criativos para",
        "Nenhum canal ativo": "Nenhum canal ativo",
        "Por favor, preencha todos os campos obrigatórios (*) e gere a URL.": "Por favor, preencha todos os campos obrigatórios (*) e gere a URL.",
        "Copiar URL": "Copiar URL",
        "Preencha os campos para gerar a URL.": "Preencha os campos para gerar a URL.",
        "Acesse sua conta": "Acesse sua conta",
        "MasterPlan": "MasterPlan",
        "Ferramenta de IA para Marketing.": "Ferramenta de IA para Marketing.",
        "Investimento Total": "Investimento Total",
        "Nenhuma campanha para este mês.": "Nenhuma campanha para este mês.",
        "Adicionar Campanhas": "Adicionar Campanhas",
        "Ver Detalhes": "Ver Detalhes",
        "Alterar foto": "Alterar foto",
        "Ou cole a URL da imagem aqui": "Ou cole a URL da imagem aqui",
        "Todos os meses já foram adicionados.": "Todos os meses já foram adicionados.",
        "Selecione um mês": "Selecione um mês",
        "Aplicar": "Aplicar",
        "Aplicado": "Aplicado",
        "Aplicar Todos": "Aplicar Todos",
        "Nenhuma sugestão gerada ou erro ao buscar sugestões.": "Nenhuma sugestão gerada ou erro ao buscar sugestões.",
        "Gerando sugestões...": "Gerando sugestões...",
        "Falha ao gerar sugestões.": "Falha ao gerar sugestões.",
        "aiSuggestionPrereqAlert": "Por favor, preencha Tipo de Campanha, Canal e Objetivo para obter uma sugestão.",
        "Não foi possível gerar la sugestão. Tente novamente.": "Não foi possível gerar la sugestão. Tente novamente.",
        "Erro ao analisar plano com IA.": "Erro ao analisar plano com IA.",
        "ou": "ou",
        "AI plan creation feature coming soon! Starting with a blank plan.": "Funcionalidade de criação de plano com IA em breve! Começando com um plano em branco.",
        "Novo Plano (IA)": "Novo Plano (IA)",
        "Usuário": "Usuário",
        "Export functionality to be implemented.": "Funcionalidade de exportação a ser implementada.",
        "Duplicate Plan": "Duplicar Plano",
        "Delete Plan": "Apagar Plano",
        "Plan Actions": "Ações do Plano",
        "Confirm Delete This Plan": "Tem certeza que deseja apagar este plano? Esta ação não pode ser desfeita.",
        "Crie seu Plano com IA": "Crie seu Plano com IA",
        "Descreva seu negócio, objetivos e público": "Descreva seu negócio, objetivos e público para a IA criar um plano de mídia inicial para você.",
        "Ex: Uma cafeteria em São Paulo focada em jovens profissionais. Objetivo: aumentar o fluxo na loja.": "Ex: Uma cafeteria em São Paulo focada em jovens profissionais. Objetivo: aumentar o fluxo na loja.",
        "Gerar Plano": "Gerar Plano",
        "Gerando seu plano...": "Gerando seu plano...",
        "Erro ao criar o plano com IA. Por favor, tente novamente.": "Erro ao criar o plano com IA. Por favor, tente novamente.",
        "A resposta da IA não retornou um plano válido.": "A resposta da IA não retornou um plano válido.",
        "Selecione um canal": "Selecione um canal primeiro",
        "Ajustar Plano com IA": "Ajustar Plano com IA",
        "Ajustar Prompt do Plano IA": "Ajustar Prompt do Plano IA",
        "Regerar Plano": "Regerar Plano",
        "Regerando plano...": "Regerando plano...",
        "Visitas": "Visitas",
        "Connect Rate (%)": "Tx. Conexão (%)",
        "seed_keywords_label": "A Partir de Palavras-Chave",
        "ai_prompt_label": "A Partir de Prompt de IA",
        "seed_keywords_placeholder": "Digite palavras-chave separadas por vírgula, ex: marketing digital, seo, mídias sociais",
        "ai_prompt_placeholder": "Descreva seu produto, serviço ou público-alvo... ex: \"Loja online de sapatos artesanais e sustentáveis para mulheres no Brasil.\"",
        "generate_keywords": "Gerar Palavras-Chave",
        "generating_keywords": "Gerando...",
        "number_of_suggestions": "Número de Sugestões",
        "keyword": "Palavra-Chave",
        "search_volume": "Volume de Busca",
        "estimated_clicks": "Cliques Estimados",
        "min_cpc": "CPC Mín.",
        "max_cpc": "CPC Máx.",
        "export_keywords": "Exportar Palavras-Chave",
        "no_keywords_generated": "Nenhuma palavra-chave gerada ainda. Use o formulário acima para começar.",
        "error_generating_keywords": "Erro ao gerar palavras-chave. Por favor, tente novamente.",
        "Results": "Resultados",
        "export_as_csv": "Exportar como CSV (.csv)",
        "export_as_txt": "Exportar como Texto (.txt)",
        "ad_groups": "Grupos de Anúncios",
        "create_ad_group": "Criar Grupo de Anúncios",
        "ad_group_name_placeholder": "Nome do novo grupo...",
        "unassigned_keywords": "Palavras-Chave Não Atribuídas",
        "assign_to_group": "Atribuir ao Grupo",
        "no_ad_groups": "Nenhum grupo de anúncio criado. Crie um para começar a organizar.",
        "export_all_keywords": "Exportar todas as palavras-chave",
        "export_unassigned": "Exportar não atribuídas",
        "export_group": "Exportar grupo '{groupName}'",
        "ad_group_column": "Grupo de Anúncio",
        "confirm_delete_group": "Tem certeza que quer apagar este grupo? As palavras-chave serão movidas para 'Não Atribuídas'.",
        "generate_images": "Gerar Imagens",
        "generating_images": "Gerando imagens...",
        "creative_prompt_placeholder": "Descreva a imagem que você quer criar em detalhes. Ex: \"Uma imagem fotorrealista de um carro elétrico futurista dirigindo em uma rua iluminada por neon em Tóquio à noite.\"",
        "creative_builder_initial_prompt": "Descreva a imagem que você deseja criar e clique em \"Gerar Imagens\" para começar.",
        "download": "Baixar",
        "download_as_jpg": "Baixar como JPG",
        "download_as_png": "Baixar como PNG",
        "error_generating_images": "Erro ao gerar imagens. Por favor, tente novamente.",
        "export_to_pdf": "Exportar para PDF",
        "generating_pdf": "Gerando PDF...",
        "share_link": "Compartilhar Link",
        "share_plan_title": "Compartilhar Plano",
        "share_plan_desc": "Qualquer pessoa com este link poderá ver uma versão somente leitura do plano.",
        "copy_link": "Copiar Link",
        "copied": "Copiado!",
        "plan_not_found": "Plano não encontrado ou indisponível.",
        "loading_plan": "Carregando plano...",
        "shared_by": "Apresentado por",
        "link_generation_error": "Não foi possível gerar o link neste ambiente.",
        "link_generation_error_too_long": "O plano é muito grande para ser compartilhado via link. Tente exportar como PDF.",
        "Prompt para Geração de Imagem": "Prompt para Geração de Imagem",
        "no_keywords_in_group": "Nenhuma palavra-chave neste grupo.",
        "add": "Adicionar",
        "move_to": "Mover para...",
        "utm_url_helper": "A URL de destino final do seu anúncio ou link. Ex: https://www.seusite.com.br/produto",
        "utm_source_helper": "Identifique a origem do tráfego. Ex: google, facebook, newsletter_email",
        "utm_medium_helper": "O meio da campanha. Ex: cpc, social, email",
        "utm_campaign_helper": "O nome da sua campanha específica. Ex: promocao_verao_2024, lancamento_produto_x",
        "utm_term_helper": "Use para identificar palavras-chave pagas. Ex: tenis_corrida_masculino",
        "utm_content_helper": "Diferencie anúncios ou links que apontam para a mesma URL. Ex: banner_azul, link_texto_CTA"
    },
    'en-US': {
        save: 'Save',
        cancel: 'Cancel',
        close: 'Close',
        edit: 'Rename', // "Edit" can be ambiguous, "Rename" is better for plans
        delete: 'Delete', // General delete
        actions: 'Actions',
        language: 'Language',
        theme: 'Theme',
        duplicate: 'Duplicate',
        my_plans: 'My Plans',
        create_new_plan: 'Create New Plan',
        welcome_to_masterplan: 'Welcome to MasterPlan!',
        create_first_plan: 'Let\'s create your first media plan. How would you like to start?',
        create_with_ai: 'Create Plan with AI',
        ai_description: 'Let our artificial intelligence create a draft for you.',
        start_blank: 'Start From Scratch',
        blank_description: 'Start from scratch and build your plan step by step.',
        create_from_template: 'Create from Template',
        template_description: 'Start with a pre-filled plan with examples to edit.',
        my_profile: 'My Profile',
        sign_out: 'Sign Out',
        overview: 'Overview',
        copy_builder: 'Copy Builder',
        utm_builder: 'UTM Builder',
        keyword_builder: 'Keyword Builder',
        creative_builder: 'Creative Builder',
        detailing: 'Detailing',
        tools: 'Tools',
        media_plan: 'Media Plan',
        configure: 'Configure',
        export: 'Export',
        Janeiro: 'January', Fevereiro: 'February', Março: 'March', Abril: 'April', Maio: 'May', Junho: 'June', Julho: 'July', Agosto: 'August', Setembro: 'September', Outubro: 'October', Novembro: 'November', Dezembro: 'December',
        "Investimento por Canal": "Investment by Channel",
        "Investimento por Tipo de Campanha": "Investment by Campaign Type",
        "Investimento por Formato": "Investment by Format",
        "Investimento por Etapa Funil": "Investment by Funnel Stage",
        "Análise Estratégica do Plano": "Strategic Plan Analysis",
        "Editar Campanha": "Edit Campaign",
        "Nova Campanha": "New Campaign",
        "Sugerir Público com IA": "Suggest Audience with AI",
        "Salvar Campanha": "Save Campaign",
        "Configurações do Plano": "Plan Settings",
        "Nome da Campanha": "Campaign Name",
        "Logotipo": "Logo",
        "Cole a URL do logotipo aqui": "Paste logo URL here",
        "Upload": "Upload",
        "Objetivo Geral": "General Objective",
        "Público-Alvo Principal": "Main Target Audience",
        "Praça": "Location",
        "Investimento Total Planejado (R$)": "Total Planned Investment ($)",
        "Resumo do Plano": "Plan Summary",
        "Objetivo": "Objective",
        "Público-Alvo": "Target Audience",
        "Investimento Planejado": "Planned Investment",
        "Investimento Previsto": "Projected Investment",
        "Período": "Period",
        "Analisar Plano com IA": "Analyze Plan with AI",
        "Performance por Mês": "Monthly Performance",
        "Adicionar Mês": "Add Month",
        "Invest. Total": "Total Invest.",
        "% Share": "% Share",
        "Impressões": "Impressions",
        "Alcance": "Reach",
        "Cliques": "Clicks",
        "Conversões": "Conversions",
        "Tx. Conversão": "Conv. Rate",
        "Totais": "Totals",
        "Investimento por Mês": "Monthly Investment",
        "Distribuição de Investimento (Geral)": "Investment Distribution (Overall)",
        "Plano de Mídia - {month}": "Media Plan - {month}",
        "Gerar Ideias": "Generate Ideas",
        "Gerando...": "Generating...",
        "Tipo": "Type",
        "Funil": "Funnel",
        "Canal": "Channel",
        "Formato": "Format",
        "Budget": "Budget",
        "Orçamento Diário": "Daily Budget",
        "Nenhuma campanha adicionada para {month}.": "No campaigns added for {month}.",
        "Totais do Mês": "Month Totals",
        "Distribuição de Investimento ({month})": "Investment Distribution ({month})",
        "Sugestões de Criativos (IA)": "Creative Suggestions (AI)",
        "Gerando ideias...": "Generating ideas...",
        "Contexto para a IA": "Context for AI",
        "Descreva o produto, público, oferta e palavras-chave para guiar a IA...": "Describe the product, audience, offer, and keywords to guide the AI...",
        "Gerar Sugestões com IA": "Generate Suggestions with AI",
        "Títulos (Headlines)": "Headlines",
        "Descrições (Descriptions)": "Descriptions",
        "Títulos Longos (Long Headlines)": "Long Headlines",
        "Nenhum grupo de criativos para {channel}": "No creative groups for {channel}",
        "Comece adicionando um novo grupo.": "Start by adding a new group.",
        "Para começar, adicione campanhas com canais definidos no seu plano de mídia.": "To begin, add campaigns with defined channels in your media plan.",
        "URL do Site *": "Website URL *",
        "Campaign Source *": "Campaign Source *",
        "Campaign Medium *": "Campaign Medium *",
        "Campaign Name *": "Campaign Name *",
        "Campaign Term": "Campaign Term",
        "Campaign Content": "Campaign Content",
        "URL Gerada": "Generated URL",
        "Salvar Link": "Save Link",
        "Limpar": "Clear",
        "Links Salvos": "Saved Links",
        "Exportar como:": "Export as:",
        "Data": "Date",
        "Campanha": "Campaign",
        "URL Completa": "Full URL",
        "Nenhum link salvo ainda.": "No saved links yet.",
        "Adicionar Mês ao Plano": "Add Month to Plan",
        "Mês": "Month",
        "Meses": "Months",
        "Editar Perfil": "Edit Profile",
        "Nome": "Name",
        "URL da Foto": "Photo URL",
        "Voltar ao Dashboard": "Back to Dashboard",
        "Planeamento de Mídia Inteligente": "Intelligent Media Planning",
        "Entrar com Google": "Sign in with Google",
        "Tipo Campanha": "Campaign Type",
        "Etapa Funil": "Funnel Stage",
        "Unidade de Compra": "Buying Unit",
        "Budget (R$)": "Budget ($)",
        "Valor da Unidade (R$)": "Unit Value ($)",
        "CPC (R$)": "CPC ($)",
        "CPA (R$)": "CPA ($)",
        "CPM (R$)": "CPM ($)",
        "CTR (%)": "CTR (%)",
        "Taxa de Conversão (%)": "Conversion Rate (%)",
        "KPI": "KPI",
        "Novo Grupo de Criativos": "New Creative Group",
        "Selecione": "Select",
        "Rename": "Rename",
        "Rename Plan": "Rename Plan",
        "Plan Name": "Plan Name",
        "Copy": "(Copy)",
        "Confirm Delete Plan": "Are you sure you want to delete this plan? This action cannot be undone.",
        "Nenhum plano encontrado": "No plans found",
        "Crie seu primeiro plano de mídia para começar.": "Create your first media plan to get started.",
        "Abrir Plano": "Open Plan",
        "Todos os direitos reservados.": "All rights reserved.",
        "Métricas Estimadas": "Estimated Metrics",
        "Adicionar Primeira Campanha": "Add First Campaign",
        "Nome do Grupo de Criativos": "Creative Group Name",
        "Gerar Sugestões com IA para este campo": "Generate suggestions with AI for this field",
        "Novo Grupo": "New Group",
        "Criativos para": "Creatives for",
        "Nenhum canal ativo": "No active channels",
        "Por favor, preencha todos os campos obrigatórios (*) e gere a URL.": "Please fill all required fields (*) and generate the URL.",
        "Copiar URL": "Copy URL",
        "Preencha os campos para gerar a URL.": "Fill the fields to generate the URL.",
        "Acesse sua conta": "Access your account",
        "MasterPlan": "MasterPlan",
        "Ferramenta de IA para Marketing.": "AI Tool for Marketing.",
        "Investimento Total": "Total Investment",
        "Nenhuma campanha para este mês.": "No campaigns for this month.",
        "Adicionar Campanhas": "Add Campaigns",
        "Ver Detalhes": "View Details",
        "Alterar foto": "Change picture",
        "Ou cole a URL da imagem aqui": "Or paste the image URL here",
        "Todos os meses já foram adicionados.": "All months have been added.",
        "Selecione um mês": "Select a month",
        "Aplicar": "Apply",
        "Aplicado": "Applied",
        "Aplicar Todos": "Apply All",
        "Nenhuma sugestão gerada ou erro ao buscar sugestões.": "No suggestions generated or error fetching suggestions.",
        "Gerando sugestões...": "Generating suggestions...",
        "Falha ao gerar sugestões.": "Failed to generate suggestions.",
        "aiSuggestionPrereqAlert": "Please fill in Campaign Type, Channel, and Objective to get a suggestion.",
        "Não foi possível gerar la sugestão. Tente novamente.": "Couldn't generate the suggestion. Try again.",
        "Erro ao analisar plano com IA.": "Error analyzing plan with AI.",
        "ou": "or",
        "AI plan creation feature coming soon! Starting with a blank plan.": "AI plan creation feature coming soon! Starting with a blank plan.",
        "Novo Plano (IA)": "New Plan (IA)",
        "Usuário": "User",
        "Export functionality to be implemented.": "Export functionality to be implemented.",
        "Duplicate Plan": "Duplicate Plan",
        "Delete Plan": "Delete Plan",
        "Plan Actions": "Plan Actions",
        "Confirm Delete This Plan": "Are you sure you want to delete this plan? This action cannot be undone.",
        "Crie seu Plano com IA": "Create your Plan with AI",
        "Descreva seu negócio, objetivos e público": "Describe your business, goals, and audience for the AI to create an initial media plan for you.",
        "Ex: Uma cafeteria em São Paulo focada em jovens profissionais. Objetivo: aumentar o fluxo na loja.": "Ex: A coffee shop in São Paulo targeting young professionals. Goal: increase store traffic.",
        "Gerar Plano": "Generate Plan",
        "Gerando seu plano...": "Generating your plan...",
        "Erro ao criar o plano com IA. Por favor, tente novamente.": "Error creating the plan with AI. Please try again.",
        "A resposta da IA não retornou um plano válido.": "The AI response did not return a valid plan.",
        "Selecione um canal": "Select a channel first",
        "Ajustar Plano com IA": "Adjust Plan with AI",
        "Ajustar Prompt do Plano IA": "Adjust AI Plan Prompt",
        "Regerar Plano": "Regenerate Plan",
        "Regerando plano...": "Regenerating plan...",
        "Visitas": "Visits",
        "Connect Rate (%)": "Connect Rate (%)",
        "seed_keywords_label": "From Seed Keywords",
        "ai_prompt_label": "From AI Prompt",
        "seed_keywords_placeholder": "Enter keywords separated by commas, e.g., digital marketing, seo, social media",
        "ai_prompt_placeholder": "Describe your product, service, or target audience... e.g., \"An online store that sells sustainable handmade shoes for women in Brazil.\"",
        "generate_keywords": "Generate Keywords",
        "generating_keywords": "Generating...",
        "number_of_suggestions": "Number of Suggestions",
        "keyword": "Keyword",
        "search_volume": "Search Volume",
        "estimated_clicks": "Estimated Clicks",
        "min_cpc": "Min. CPC",
        "max_cpc": "Max. CPC",
        "export_keywords": "Export Keywords",
        "no_keywords_generated": "No keywords generated yet. Use the form above to get started.",
        "error_generating_keywords": "Error generating keywords. Please try again.",
        "Results": "Results",
        "export_as_csv": "Export as CSV (.csv)",
        "export_as_txt": "Export as Text (.txt)",
        "ad_groups": "Ad Groups",
        "create_ad_group": "Create Ad Group",
        "ad_group_name_placeholder": "New group name...",
        "unassigned_keywords": "Unassigned Keywords",
        "assign_to_group": "Assign to Group",
        "no_ad_groups": "No ad groups created. Create one to start organizing.",
        "export_all_keywords": "Export all keywords",
        "export_unassigned": "Export unassigned",
        "export_group": "Export group '{groupName}'",
        "ad_group_column": "Ad Group",
        "confirm_delete_group": "Are you sure you want to delete this group? Keywords will be moved to 'Unassigned'.",
        "generate_images": "Generate Images",
        "generating_images": "Generating images...",
        "creative_prompt_placeholder": "Describe the image you want to create in detail. E.g., \"A photorealistic image of a futuristic electric car driving on a neon-lit street in Tokyo at night.\"",
        "creative_builder_initial_prompt": "Describe the image you want to create and click \"Generate Images\" to start.",
        "download": "Download",
        "download_as_jpg": "Download as JPG",
        "download_as_png": "Download as PNG",
        "error_generating_images": "Error generating images. Please try again.",
        "export_to_pdf": "Export to PDF",
        "generating_pdf": "Generating PDF...",
        "share_link": "Share Link",
        "share_plan_title": "Share Plan",
        "share_plan_desc": "Anyone with this link can view a read-only version of the plan.",
        "copy_link": "Copy Link",
        "copied": "Copied!",
        "plan_not_found": "Plan not found or unavailable.",
        "loading_plan": "Loading plan...",
        "shared_by": "Presented by",
        "link_generation_error": "Could not generate link in this environment.",
        "link_generation_error_too_long": "This plan is too large to be shared via a link. Try exporting to PDF instead.",
        "Prompt para Geração de Imagem": "Image Generation Prompt",
        "no_keywords_in_group": "No keywords in this group.",
        "add": "Add",
        "move_to": "Move to...",
        "utm_url_helper": "The final destination URL of your ad or link. E.g., https://www.yoursite.com/product",
        "utm_source_helper": "Identify the source of the traffic. E.g., google, facebook, email_newsletter",
        "utm_medium_helper": "The campaign medium. E.g., cpc, social, email",
        "utm_campaign_helper": "The name of your specific campaign. E.g., summer_sale_2024, product_x_launch",
        "utm_term_helper": "Use to identify paid keywords. E.g., mens_running_shoes",
        "utm_content_helper": "Differentiate ads or links that point to the same URL. E.g., blue_banner, text_link_CTA"
    }
};